// 50 questions for one person. Inspired by Arthur Aron's 36 — stripped of every
// "you and your partner"; the only other person in the room is you.
// Arc: surface → middle → marrow.
export const QUESTIONS = [
  // I. SURFACE
  "What did you want to become before anyone asked you to be realistic?",
  "When did you last catch yourself performing an enthusiasm you didn't feel?",
  "Describe your perfect day, hour by hour. Which hour would you actually defend?",
  "What do your hands do when nobody is watching them?",
  "Which of your habits is actually a ritual — and what is the ritual protecting?",
  "What would you attempt if failure were guaranteed to stay private?",
  "What did you last rehearse saying in the shower, and to whom was it really addressed?",
  "Which compliment do you deflect the fastest? That one is true.",
  "What is the oldest object you refuse to throw away, and what memory is stored in it?",
  "If your body kept a log file, what would be the most frequent entry?",
  "What noise does your mind default to in an empty room?",
  "Which small pleasure do you ration, as if it could run out?",
  // II. MIDDLE
  "What are you grateful for that you never say out loud, in case saying it breaks it?",
  "If you could change one thing about how you were raised — what did that same thing also give you?",
  "Take four minutes. Tell yourself your life story. Notice what you left out.",
  "If you woke tomorrow with one new ability, what deficit would it be compensating?",
  "What is the experiment you have postponed for years — and which result are you afraid of?",
  "What is the greatest accomplishment of your life by your own metric, not the one you cite in company?",
  "What do you value most in a friend — and do you supply it to yourself?",
  "What is your most treasured memory, and how much of it have you edited?",
  "What is your most terrible memory, and what did it train you to detect?",
  "If you knew you had one year left, what would you change — and why does it require a deadline?",
  "What does friendship with yourself look like? Have you started it?",
  "What roles do love and tenderness play in your life when nobody assigns them to you?",
  "Name something you like about yourself that took years to admit.",
  "How did your childhood define what safety feels like — and is that definition still accurate?",
  "Describe your relationship with your mother in one clinical sentence. Now read it back.",
  "Finish: 'I wish I had someone with whom I could share…' Now ask why that someone cannot be you.",
  "What should you know about yourself by now that you keep failing the exam on?",
  "Which embarrassing moment do you still replay — and who exactly is the audience in the replay?",
  "When did you last cry alone — and was the trigger the event, or the accumulated load?",
  // III. MARROW
  "What is too serious for you to joke about, and what happened to make it so?",
  "If you died tonight with no chance to speak to anyone, what would you regret not having said — and why is it still unsaid?",
  "Your house is burning; every living thing is safe; you may save one object. Which — and what is it a container for?",
  "Which death rearranged you the most, and what exactly did it rearrange?",
  "What weight are you carrying right now that you keep describing as lighter than it is?",
  "Which of your problems would sound trivial to a stranger and unbearable to you? Both readings are correct.",
  "What do you feel the moment you stop moving? Is that why you keep moving?",
  "Which part of your identity did you build, and which part was assigned — and which one do you defend harder?",
  "What are you homesick for that is not a place?",
  "Which version of you had to be abandoned so this one could exist? Did you ever thank it?",
  "What pain have you converted into productivity, and what was the exchange rate?",
  "Which lie about yourself do you tell so well that you now pass your own detection?",
  "What forgiveness are you withholding from yourself, and on what evidence?",
  "If your fear could speak in complete sentences, what is the first thing it would explain to you?",
  "What did you survive that you have never once called survival?",
  "What do you want no gravestone to say, but everyone to somehow know?",
  "When were you last fully seen — and what did you do to end the exposure?",
  "What are you becoming that you haven't announced yet?",
  "If you met yourself as a stranger tonight, in this field — would you stay?"
];
